Feat/reservation checked
manito42/backend pull request #72
Opened 2023-09-05 15:05 UTC by koreanddinghwan

2023-09-05 15:10 UTC, koreanddinghwan commented
build bot에 prisma generate 추가해뒀습니다

2023-09-06 05:38 UTC, JuneParkCode requested changes

2023-09-06 05:38 UTC, JuneParkCode commented on src/database/repository/reservation.repository.ts
> +      )
`reservation.status !== ReservationStatus.MENTEE_CHECKED` 이거만 필요한거 아닌가요?

2023-09-06 05:44 UTC, koreanddinghwan commented on src/database/repository/reservation.repository.ts
> +      )
프론트엔드에서 check api를 정확하게 어떻게 사용할지 예측하지 못해서 열어뒀습니다.  

check하지 않은 상태에서 mentor의 프로필을 알고 있으니, check절차를 거치지 않고 멘토링 진행할수도 있다고 생각했습니다.

2023-09-06 05:54 UTC, JuneParkCode commented on src/database/repository/reservation.repository.ts
> +      )
오키 납득가네요 그대로가요

2023-09-06 06:28 UTC, JuneParkCode approved these changes

2023-09-06 06:33 UTC, merged